apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter-app
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter-app
  template:
    metadata:
      labels:
        app: tempconverter-app
    spec:
      containers:
        - name: app
          image: ghcr.io/sehnryr/tempconverter:dev
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              value: username
            - name: DB_PASS
              value: supersecretpassword
            - name: DB_HOST
              value: tempconverter-db
            - name: DB_NAME
              value: dbname
            - name: STUDENT
              value: "Youn Mélois"
            - name: COLLEGE
              value: "Algebra University College"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
