apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  namespace: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/db-data
