apiVersion: v1
kind: Service
metadata:
  name: tempconverter-app
  namespace: local
spec:
  selector:
    app: tempconverter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
