apiVersion: v1
kind: Service
metadata:
  name: tempconverter-db
  namespace: local
spec:
  selector:
    app: tempconverter-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
