version: '3.8'

services:
  app:
    image: ghcr.io/sehnryr/tempconverter:dev
    ports:
      - "80:5000"
    environment:
      DB_USER: username
      DB_PASS: supersecretpassword
      DB_HOST: db
      DB_NAME: dbname
      STUDENT: Youn Mélois
      COLLEGE: Algebra University College
    depends_on:
      - db
    networks:
      - tempconverter-network
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

  db:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: supersecretpassword
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tempconverter-network
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  tempconverter-network:
    driver: overlay

volumes:
  db-data:
